In [1]:
import numpy as np

## Basics

In [2]:
# Create a 1-D array
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
# Create a 2-D array
b = np.array([[1,2,3],[4,5,6]])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
# Create a 3-D array
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [9]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [11]:
# Get the dimension of an array -array.ndim

In [12]:
print(a.ndim,"-D array")

1 -D array


In [13]:
print(b.ndim,"-D array")

2 -D array


In [14]:
print(c.ndim,"-D array")

3 -D array


In [15]:
# Get the shape of an array

In [16]:
a.shape

(3,)

In [17]:
b.shape  #2-Rows,3-Columns

(2, 3)

In [18]:
c.shape # 2-D, 2-Rows,3-Columns

(2, 2, 3)

In [19]:
# Get size- number of elements in an array

In [20]:
a.size

3

In [21]:
b.size

6

In [22]:
c.size

12

In [23]:
# nbytes - gets the total bytes consumed by the elements of the array

In [24]:
a.nbytes

12

In [25]:
b.nbytes

24

In [26]:
c.nbytes

48

## Accessing / changing specific elements, rows,columns ...

In [27]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# Get a specific element [r,c]

In [29]:
# Get the element 6 
b[1,2]

6

In [30]:
# Get the element 2
b[0,1]

2

In [31]:
# Get a specific element row/column

In [32]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
b[0]

array([1, 2, 3])

In [34]:
b[1]

array([4, 5, 6])

In [35]:
b[:,0]

array([1, 4])

In [36]:
b[:,1]

array([2, 5])

In [37]:
b[:,2]

array([3, 6])

In [38]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
b[1] = 9

In [40]:
b

array([[1, 2, 3],
       [9, 9, 9]])

In [41]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
c[0,0::,1::]

array([[2, 3],
       [5, 6]])

In [43]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [44]:
# Get [8,  9]
#    [ 11,  12]

In [45]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
c[1,0::,1::]

array([[ 8,  9],
       [11, 12]])

### Initializing Different Types of Array

In [47]:
# An array of all Zeros

In [48]:
d = np.zeros(3)
print(d)

[0. 0. 0.]


In [49]:
e = np.zeros((3,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [50]:
# An array of all ones
f = np.ones(5)
print(f)

[1. 1. 1. 1. 1.]


In [51]:
g = np.ones((5,5))
print(g)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [52]:
# Any other number

In [53]:
h = np.full(5,4)
print(h)

[4 4 4 4 4]


In [54]:
h = np.full((5,4),4)
print(h)

[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


In [55]:
# identity matrix
i = np.identity(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [56]:
i = np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
# Random intergers and random decimal numbers

In [58]:
j = np.random.rand(4)
print(j)

[0.67735505 0.0285866  0.9333346  0.73871324]


In [59]:
j = np.random.rand(4,5)
print(j)

[[0.54136347 0.12330709 0.41777895 0.27168979 0.52911321]
 [0.06898369 0.39650177 0.68245349 0.32633278 0.24779354]
 [0.75322719 0.80425154 0.08406381 0.0978157  0.05037009]
 [0.67087335 0.51674647 0.71795903 0.43172353 0.44399681]]


In [60]:
j = np.random.randint(5)
print(j)

4


In [61]:
j = np.random.randint((5,4))
print(j)

[4 0]


#### Mathematics

In [62]:
arr = np.array([4,6,8,10,12])
print(arr)

[ 4  6  8 10 12]


In [63]:
arr + 2

array([ 6,  8, 10, 12, 14])

In [64]:
arr - 2

array([ 2,  4,  6,  8, 10])

In [65]:
arr /2 

array([2., 3., 4., 5., 6.])

In [66]:
arr * 2

array([ 8, 12, 16, 20, 24])

In [67]:
np.cos(arr)

array([-0.65364362,  0.96017029, -0.14550003, -0.83907153,  0.84385396])

In [68]:
np.sin([arr])

array([[-0.7568025 , -0.2794155 ,  0.98935825, -0.54402111, -0.53657292]])

### Linear Algebra

In [69]:
arr

array([ 4,  6,  8, 10, 12])

In [70]:
arr2 = np.array([1,3,5,7,9])

In [71]:
arr * arr2

array([  4,  18,  40,  70, 108])

In [72]:
arr3 = np.array([[1,2],[3,4]])

In [73]:
arr3

array([[1, 2],
       [3, 4]])

In [85]:
arr4 = np.array([[5,6],[7,8]])

In [86]:
arr4

array([[5, 6],
       [7, 8]])

In [87]:
np.add(arr3,arr4)

array([[ 6,  8],
       [10, 12]])

In [88]:
arr4 - arr3

array([[4, 4],
       [4, 4]])

In [99]:
#multiplication of two matrices
np.matmul(arr3,arr4)

array([[19, 22],
       [43, 50]])

In [89]:
np.matmul(arr3,arr4)

array([[19, 22],
       [43, 50]])

In [100]:
# Finding the determinant
np.linalg.det(arr3)

-2.0000000000000004

In [135]:
Id = np.identity(2)

In [136]:
Id

array([[1., 0.],
       [0., 1.]])

In [137]:
np.linalg.det(Id)

1.0

### Statistics

In [80]:
arr3

array([[1, 2],
       [3, 4]])

In [81]:
arr3.max()

4

In [82]:
arr3.min()

1

In [83]:
arr3.mean()

2.5

#### Load Data From File

In [122]:
data = np.genfromtxt("numbers.txt",delimiter=",")
data= data.astype("int32")
data

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [118]:
Data = np.genfromtxt("numbers.txt", delimiter=",")

#### Boolean Masking

In [123]:
data > 5

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [131]:
data % 2 == 0

array([[False,  True, False,  True],
       [ True, False,  True, False],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [132]:
data[data % 2 == 0]

array([ 2,  4,  6,  8, 12, 14, 16, 18])

In [134]:
data > 10

array([[False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [133]:
data[data > 10]

array([11, 12, 13, 14, 15, 16, 17, 18])

In [129]:
data

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])